---
- name: my first task
  hosts: localhost
  tasks:
    # this is a test task
    - name: print
      debug:
        msg: "welcome to devspaces"

    - name: checking the devspaces
      debug:
        msg: "my first  - devspace"

    - name: starting  a service
      ansible.builtin.service:
        name: httpd
        state: started
