---
- name: my first task
  hosts: localhost
  tasks:
    # this is a test task
    - name: print
      debug:
        msg: "welcome to devspaces"
    - name: Display message
      ansible.builtin.debug:
        msg: "my dev spaces are working"

    - name: starting  a service
      ansible.builtin.service:
        name: httpd
        state: started
